/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What people are on now, and their hours today and this week */
        get: operations["list-activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent changes to payroll data */
        get: operations["list-audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clock/in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start the caller's clock */
        post: operations["clock-in"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clock/out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop the caller's clock */
        post: operations["clock-out"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clock/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move the caller's running clock to other work */
        post: operations["clock-switch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customers */
        get: operations["list-customers"];
        put?: never;
        /** Add a customer */
        post: operations["create-customer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Rename or archive a customer */
        put: operations["update-customer"];
        post?: never;
        /** Delete a customer with no projects */
        delete: operations["delete-customer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A person's time on a range of days */
        get: operations["list-entries"];
        put?: never;
        /** Record finished time by hand */
        post: operations["create-entry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change an entry */
        put: operations["update-entry"];
        post?: never;
        /** Delete an entry */
        delete: operations["delete-entry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What payroll should look at in a pay period */
        get: operations["list-exceptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Where Timeclock runs and how to sign in */
        get: operations["get-info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is calling, and how payroll runs */
        get: operations["get-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/timezone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the time zone the caller's days are cut in */
        put: operations["set-own-timezone"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The people whose time the caller may see */
        get: operations["list-people"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bring in everyone from the directory */
        post: operations["sync-people"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set a person's manager and payroll details */
        put: operations["update-person"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects, by customer */
        get: operations["list-projects"];
        put?: never;
        /** Add a project */
        post: operations["create-project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change or archive a project */
        put: operations["update-project"];
        post?: never;
        /** Delete a project with no time on it */
        delete: operations["delete-project"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hours by day and project */
        get: operations["hours-by-day"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/payroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everyone's hours for a pay period */
        get: operations["payroll-report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/payroll.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A pay period's hours as a file for the payroll system */
        get: operations["payroll-export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hours by customer, project and person */
        get: operations["project-report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/projects.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hours by customer, project and person, as a file */
        get: operations["project-export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change how payroll runs */
        put: operations["update-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The pay period of everyone whose time the caller may see */
        get: operations["get-team"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A person's time off on a range of days */
        get: operations["list-time-off"];
        put?: never;
        /** Record vacation or sick time on a run of days */
        post: operations["request-time-off"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time-off/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time off waiting for the caller's decision */
        get: operations["list-pending-time-off"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time-off/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a day of time off */
        delete: operations["cancel-time-off"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time-off/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or reject time off */
        post: operations["decide-time-off"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/timesheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A person's pay period: hours by day and its timesheet */
        get: operations["get-timesheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/timesheet/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** State that a pay period's time is complete */
        post: operations["submit-timesheet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/timesheets/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a timesheet or send it back */
        post: operations["decide-timesheet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/timesheets/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock a timesheet so its time can be corrected */
        post: operations["reopen-timesheet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Activity: {
            person: components["schemas"]["Person"];
            /** @description Their running clock. */
            running?: components["schemas"]["Entry"];
            /**
             * Format: double
             * @description Hours today, with the running clock up to now.
             */
            today: number;
            /**
             * Format: double
             * @description Hours this workweek, with the running clock up to now.
             */
            week: number;
        };
        AuditEntry: {
            action: string;
            actor: string;
            /** Format: date-time */
            at: string;
            detail: {
                [key: string]: unknown;
            };
            id: string;
            personId?: string;
        };
        "Clock-inRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Clock-inRequest.json
             */
            readonly $schema?: string;
            note?: string;
            projectId?: string;
        };
        "Clock-switchRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Clock-switchRequest.json
             */
            readonly $schema?: string;
            note?: string;
            projectId?: string;
        };
        Customer: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Customer.json
             */
            readonly $schema?: string;
            archived: boolean;
            id: string;
            name: string;
        };
        CustomerInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/CustomerInput.json
             */
            readonly $schema?: string;
            archived?: boolean;
            name: string;
        };
        DayProjectHours: {
            /** Format: date */
            day: string;
            /** Format: double */
            hours: number;
            /** @description Empty for time with no project. */
            projectId: string;
        };
        DaySummary: {
            /** Format: date */
            day: string;
            /** Format: double */
            overtime: number;
            /** Format: double */
            regular: number;
            /** Format: double */
            sick: number;
            /** Format: double */
            vacation: number;
        };
        Decision: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Decision.json
             */
            readonly $schema?: string;
            /** @description False sends it back. */
            approve: boolean;
            note?: string;
        };
        Entry: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Entry.json
             */
            readonly $schema?: string;
            /**
             * Format: date-time
             * @description Absent while the clock is running.
             */
            endedAt?: string;
            id: string;
            /** @description In a submitted or approved timesheet, so it can't change. */
            locked: boolean;
            note: string;
            personId: string;
            projectId?: string;
            /** @enum {string} */
            source: "clock" | "manual";
            /** Format: date-time */
            startedAt: string;
        };
        EntryInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/EntryInput.json
             */
            readonly $schema?: string;
            /**
             * Format: date-time
             * @description Absent leaves a running clock running.
             */
            endedAt?: string;
            note?: string;
            /** @description Whose time it is. Defaults to the caller; a manager or admin can record time for someone else. */
            personId?: string;
            projectId?: string;
            /** Format: date-time */
            startedAt: string;
        };
        Exception: {
            /** Format: date */
            day?: string;
            entryId?: string;
            /**
             * Format: double
             * @description The hours the exception is about: the entry's length, the overtime, or the pending time off.
             */
            hours?: number;
            /** @enum {string} */
            kind: "clock_running" | "long_entry" | "not_submitted" | "awaiting_approval" | "rejected" | "time_off_pending" | "overtime" | "no_time";
            personId: string;
            personName: string;
        };
        ExceptionsBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ExceptionsBody.json
             */
            readonly $schema?: string;
            exceptions: components["schemas"]["Exception"][] | null;
            period: components["schemas"]["Period"];
        };
        FieldError: {
            /** @description Stable name of the rule, for clients to show a localized message. New codes can appear: fall back to a generic message for one you don't know. */
            code: string;
            /** @description Explanation, in the language the Content-Language header names; English without it. */
            detail?: string;
            /**
             * @description Where parameter is.
             * @enum {string}
             */
            in?: "query" | "path" | "header" | "cookie";
            /** @description Name of the invalid request parameter. */
            parameter?: string;
            /** @description Values the rule's localized message shows. */
            params?: {
                [key: string]: unknown;
            };
            /** @description JSON Pointer to the invalid body field, as a URI fragment such as #/items/0/name. */
            pointer?: string;
            /**
             * Format: uri-reference
             * @description The rule's problem type.
             */
            type: string;
        };
        "Hours-by-dayResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Hours-by-dayResponse.json
             */
            readonly $schema?: string;
            rows: components["schemas"]["DayProjectHours"][] | null;
        };
        Info: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Info.json
             */
            readonly $schema?: string;
            homeLabel?: string;
            homeUrl?: string;
            signInUrl?: string;
            signOutUrl?: string;
            themeStorageKey?: string;
        };
        "List-activityResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/List-activityResponse.json
             */
            readonly $schema?: string;
            people: components["schemas"]["Activity"][] | null;
        };
        "List-auditResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/List-auditResponse.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["AuditEntry"][] | null;
        };
        "List-customersResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/List-customersResponse.json
             */
            readonly $schema?: string;
            customers: components["schemas"]["Customer"][] | null;
        };
        "List-entriesResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/List-entriesResponse.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["Entry"][] | null;
        };
        "List-projectsResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/List-projectsResponse.json
             */
            readonly $schema?: string;
            projects: components["schemas"]["Project"][] | null;
        };
        MeBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/MeBody.json
             */
            readonly $schema?: string;
            /** @description Runs payroll: sees everyone, approves anything, changes settings, exports reports. */
            admin: boolean;
            info: components["schemas"]["Info"];
            /** @description Has people whose time they approve. */
            manager: boolean;
            /** @description The current pay period. */
            period: components["schemas"]["Period"];
            person: components["schemas"]["Person"];
            /** @description The caller's running clock. */
            running?: components["schemas"]["Entry"];
            settings: components["schemas"]["Settings"];
            /**
             * Format: date
             * @description Today in the organization's time zone.
             */
            today: string;
        };
        PayrollBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/PayrollBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            notReady: number;
            period: components["schemas"]["Period"];
            rows: components["schemas"]["PayrollRow"][] | null;
        };
        PayrollRow: {
            days: components["schemas"]["DaySummary"][] | null;
            /** Format: double */
            overtime: number;
            /** Format: double */
            pendingTimeOff: number;
            period: components["schemas"]["Period"];
            person: components["schemas"]["Person"];
            /** @description The person's time is settled for this period: approved, or submitted when timesheets need no approval. Only ready people are in the export. */
            ready: boolean;
            /** Format: double */
            regular: number;
            /** @description A clock is running; its time isn't counted until it stops. */
            running: boolean;
            /**
             * Format: double
             * @description Approved sick hours.
             */
            sick: number;
            /** @description Absent until the person submits. */
            timesheet?: components["schemas"]["Timesheet"];
            /**
             * Format: double
             * @description Approved vacation hours.
             */
            vacation: number;
        };
        PeopleBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/PeopleBody.json
             */
            readonly $schema?: string;
            people: components["schemas"]["Person"][] | null;
        };
        Period: {
            /** Format: date */
            end: string;
            /** Format: date */
            start: string;
        };
        PeriodSummary: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/PeriodSummary.json
             */
            readonly $schema?: string;
            days: components["schemas"]["DaySummary"][] | null;
            /** Format: double */
            overtime: number;
            /** Format: double */
            pendingTimeOff: number;
            period: components["schemas"]["Period"];
            person: components["schemas"]["Person"];
            /** Format: double */
            regular: number;
            /** @description A clock is running; its time isn't counted until it stops. */
            running: boolean;
            /**
             * Format: double
             * @description Approved sick hours.
             */
            sick: number;
            /** @description Absent until the person submits. */
            timesheet?: components["schemas"]["Timesheet"];
            /**
             * Format: double
             * @description Approved vacation hours.
             */
            vacation: number;
        };
        Person: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Person.json
             */
            readonly $schema?: string;
            active: boolean;
            email: string;
            id: string;
            /** @description Who approves this person's time; empty when no one is assigned. */
            managerId: string;
            name: string;
            overtimeExempt: boolean;
            /** @description The person's id in the payroll system, for the export. */
            payrollId: string;
            /**
             * @description The IANA time zone their days and workweeks are cut in; empty uses the organization's.
             * @example America/Los_Angeles
             */
            timezone: string;
        };
        PersonUpdate: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/PersonUpdate.json
             */
            readonly $schema?: string;
            /** @description Inactive people are left out of payroll reports and exceptions. */
            active: boolean;
            /** @description Who approves this person's time. Empty defers to the host's directory. */
            managerId: string;
            overtimeExempt: boolean;
            payrollId: string;
            /** @description The IANA time zone their days are cut in. Empty uses the organization's. */
            timezone: string;
        };
        Problem: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Problem.json
             */
            readonly $schema?: string;
            /** @description Stable name of the problem type, for clients to show a localized message. New codes can appear: fall back to the status for one you don't know. Absent for about:blank: derive it from the status. */
            code?: string;
            /** @description Explanation of this occurrence, in the language the Content-Language header names. Without that header it is English, for developers and logs: show your own message for code instead. */
            detail?: string;
            /** @description For a validation problem, each invalid field and the rule it failed. */
            errors?: components["schemas"]["FieldError"][] | null;
            /**
             * Format: uri-reference
             * @description Identifies this occurrence of the problem.
             */
            instance?: string;
            /** @description Values the code's localized message shows. */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Format: int64
             * @description The HTTP status code.
             */
            status?: number;
            /** @description Short English summary of the problem type, for developers. */
            title?: string;
            /**
             * Format: uri-reference
             * @description Identifies the problem type and resolves to its documentation. about:blank means nothing beyond the status.
             */
            type: string;
        };
        Project: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Project.json
             */
            readonly $schema?: string;
            /** @description The project itself is archived. */
            archived: boolean;
            billable: boolean;
            /** @description A charge code or contract number. */
            code: string;
            customerArchived: boolean;
            /** @description Absent for internal work. */
            customerId?: string;
            /** @description Empty for internal work. */
            customerName: string;
            id: string;
            name: string;
        };
        ProjectHours: {
            billable: boolean;
            customerName: string;
            /** Format: double */
            hours: number;
            personId: string;
            personName: string;
            projectCode: string;
            /** @description Empty for time with no project. */
            projectId: string;
            projectName: string;
        };
        ProjectInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ProjectInput.json
             */
            readonly $schema?: string;
            archived?: boolean;
            billable: boolean;
            /** @description A charge code or contract number. */
            code?: string;
            /** @description Absent for internal work. */
            customerId?: string;
            name: string;
        };
        ProjectsBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ProjectsBody.json
             */
            readonly $schema?: string;
            rows: components["schemas"]["ProjectHours"][] | null;
        };
        "Reopen-timesheetRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Reopen-timesheetRequest.json
             */
            readonly $schema?: string;
            note?: string;
        };
        "Set-own-timezoneRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Set-own-timezoneRequest.json
             */
            readonly $schema?: string;
            /**
             * @description An IANA time zone. Empty uses the organization's.
             * @example America/Los_Angeles
             */
            timezone: string;
        };
        Settings: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Settings.json
             */
            readonly $schema?: string;
            /** @description Time off waits for the person's manager or an admin. */
            approveTimeOff: boolean;
            /** @description A submitted timesheet waits for the person's manager or an admin. */
            approveTimesheets: boolean;
            /**
             * Format: date
             * @description The first day of some weekly or biweekly pay period.
             */
            cycleAnchor: string;
            /**
             * Format: double
             * @description An entry or a running clock longer than this is an exception.
             */
            longEntryHours: number;
            /**
             * Format: double
             * @description Hours in a workweek beyond which time is overtime. 0 turns overtime off.
             */
            overtimeWeeklyHours: number;
            /** @enum {string} */
            payCycle: "weekly" | "biweekly" | "semimonthly" | "monthly";
            /** @description Every time entry names a project. */
            requireProject: boolean;
            /**
             * @description IANA time zone that days and workweeks are cut in for everyone who hasn't set their own.
             * @example America/Chicago
             */
            timezone: string;
            /**
             * Format: int64
             * @description The day the workweek starts, for overtime: 0 is Sunday.
             */
            weekStart: number;
        };
        "Submit-timesheetRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Submit-timesheetRequest.json
             */
            readonly $schema?: string;
            /**
             * Format: date
             * @description Any day in the pay period.
             */
            day: string;
            /** @description Whose. Defaults to the caller. */
            personId?: string;
        };
        TeamBodyBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/TeamBodyBody.json
             */
            readonly $schema?: string;
            members: components["schemas"]["PeriodSummary"][] | null;
            period: components["schemas"]["Period"];
        };
        TimeOff: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/TimeOff.json
             */
            readonly $schema?: string;
            /** Format: date */
            day: string;
            /** Format: date-time */
            decidedAt?: string;
            decidedBy?: string;
            decidedByName?: string;
            decisionNote?: string;
            /** Format: double */
            hours: number;
            id: string;
            /** @enum {string} */
            kind: "vacation" | "sick";
            /** @description Its day is in a submitted or approved timesheet, so it can't be removed. */
            locked: boolean;
            note: string;
            personId: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected";
        };
        TimeOffInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/TimeOffInput.json
             */
            readonly $schema?: string;
            /** Format: date */
            from: string;
            /**
             * Format: double
             * @description Hours off on each day.
             */
            hours: number;
            /** @enum {string} */
            kind: "vacation" | "sick";
            note?: string;
            /** @description Whose time off. Defaults to the caller; a manager or admin can record it for someone else. */
            personId?: string;
            /**
             * Format: date
             * @description The last day off; the same as from for one day.
             */
            to: string;
            /** @description Include Saturdays and Sundays in the run. */
            weekends?: boolean;
        };
        TimeOffListBodyBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/TimeOffListBodyBody.json
             */
            readonly $schema?: string;
            timeOff: components["schemas"]["TimeOff"][] | null;
        };
        Timesheet: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Timesheet.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            decidedAt?: string;
            /** @description Who approved it or sent it back; the person themselves when they took it back. */
            decidedBy?: string;
            decidedByName?: string;
            decisionNote?: string;
            id: string;
            period: components["schemas"]["Period"];
            personId: string;
            /** @enum {string} */
            status: "submitted" | "approved" | "rejected";
            /** Format: date-time */
            submittedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List-activityResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-audit": {
        parameters: {
            query?: {
                /** @description Only changes to this person's time. */
                person?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List-auditResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "clock-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Clock-inRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "clock-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "clock-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Clock-switchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-customers": {
        parameters: {
            query?: {
                /** @description Include archived ones. */
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List-customersResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "create-customer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "update-customer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "delete-customer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-entries": {
        parameters: {
            query: {
                /** @description Whose. Defaults to the caller. */
                person?: string;
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List-entriesResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "create-entry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "update-entry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "delete-entry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-exceptions": {
        parameters: {
            query?: {
                /** @description Any day in the pay period. Defaults to today. */
                day?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionsBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "get-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Info"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "get-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "set-own-timezone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Set-own-timezoneRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "sync-people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "update-person": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-projects": {
        parameters: {
            query?: {
                /** @description Include archived ones. */
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List-projectsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "create-project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "update-project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "delete-project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "hours-by-day": {
        parameters: {
            query: {
                from: string;
                to: string;
                /** @description Only the caller's own time, rather than everyone's they may see. */
                mine?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hours-by-dayResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "payroll-report": {
        parameters: {
            query?: {
                /** @description Any day in the pay period. Defaults to today. */
                day?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayrollBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "payroll-export": {
        parameters: {
            query?: {
                /** @description Any day in the pay period. Defaults to today. */
                day?: string;
                /** @description Include people whose time isn't settled. */
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "project-report": {
        parameters: {
            query: {
                /** @description Whose. Defaults to the caller. */
                person?: string;
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "project-export": {
        parameters: {
            query: {
                /** @description Whose. Defaults to the caller. */
                person?: string;
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "update-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "get-team": {
        parameters: {
            query?: {
                /** @description Any day in the pay period. Defaults to today. */
                day?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamBodyBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-time-off": {
        parameters: {
            query: {
                /** @description Whose. Defaults to the caller. */
                person?: string;
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOffListBodyBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "request-time-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeOffInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOffListBodyBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-pending-time-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOffListBodyBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "cancel-time-off": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "decide-time-off": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOff"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "get-timesheet": {
        parameters: {
            query?: {
                /** @description Whose. Defaults to the caller. */
                person?: string;
                /** @description Any day in the pay period. Defaults to today. */
                day?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodSummary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "submit-timesheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Submit-timesheetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodSummary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "decide-timesheet": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timesheet"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "reopen-timesheet": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reopen-timesheetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timesheet"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
