/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TimeOffRouteImport } from './routes/time-off'
import { Route as TimesheetRouteImport } from './routes/timesheet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeOffRoute = TimeOffRouteImport.update({
  id: '/time-off',
  path: '/time-off',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesheetRoute = TimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot': typeof ForgotRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/reports': typeof ReportsRoute
  '/reset': typeof ResetRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/time-off': typeof TimeOffRoute
  '/timesheet': typeof TimesheetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot': typeof ForgotRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/reports': typeof ReportsRoute
  '/reset': typeof ResetRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/time-off': typeof TimeOffRoute
  '/timesheet': typeof TimesheetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot': typeof ForgotRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/reports': typeof ReportsRoute
  '/reset': typeof ResetRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/time-off': typeof TimeOffRoute
  '/timesheet': typeof TimesheetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/forgot'
    | '/invite'
    | '/login'
    | '/overview'
    | '/reports'
    | '/reset'
    | '/settings'
    | '/team'
    | '/time-off'
    | '/timesheet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/forgot'
    | '/invite'
    | '/login'
    | '/overview'
    | '/reports'
    | '/reset'
    | '/settings'
    | '/team'
    | '/time-off'
    | '/timesheet'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/forgot'
    | '/invite'
    | '/login'
    | '/overview'
    | '/reports'
    | '/reset'
    | '/settings'
    | '/team'
    | '/time-off'
    | '/timesheet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ForgotRoute: typeof ForgotRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  ReportsRoute: typeof ReportsRoute
  ResetRoute: typeof ResetRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  TimeOffRoute: typeof TimeOffRoute
  TimesheetRoute: typeof TimesheetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-off': {
      id: '/time-off'
      path: '/time-off'
      fullPath: '/time-off'
      preLoaderRoute: typeof TimeOffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timesheet': {
      id: '/timesheet'
      path: '/timesheet'
      fullPath: '/timesheet'
      preLoaderRoute: typeof TimesheetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ForgotRoute: ForgotRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  ReportsRoute: ReportsRoute,
  ResetRoute: ResetRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  TimeOffRoute: TimeOffRoute,
  TimesheetRoute: TimesheetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
